#!/bin/bash
# Nagios plugin to work with Pihole API
########### By @deividgdt ###########
plugin_version="2.0"
#####################################

current_dir="$(pwd)"

function info() {
	case "$1" in
		token)
			echo "[i] The file ${api_token_file} does not exist or it's empty."
			echo "[i] You can get your token from the value WEBPASSWORD in the file /etc/pihole/setupVars.conf"
			echo "[i] Just put in the file ${api_token_file} and that's it."
			echo ""
			echo "[i] Example:"
			echo "	centreon-engine@centreon # touch ${api_token_file}"
			echo "	centreon-engine@centreon # echo 'PASTE_YOUR_TOKEN_HERE' >> ${api_token_file}"
			exit 1;
		;;
		usage)
			echo "[i] Usage $0 -h pihole_ipaddress -p [ http || https ] -s [ clients || queries || ads ] || -i || -q || -t"
			echo ""
			echo "[i] -s (summary)"
			echo "	- clients: Number of clients using Pihole as their DNS server"
			echo "	- queries: Number of DNS queries"
			echo "	- ads: Number and percentage of ads blocked."
			echo ""
			echo "[i] -p (protocol)"
			echo "	- Protocol to be used in the API call (http||https). By default: http"
			echo ""
			echo "[i] -i (information)"
			echo "	- show the version of the plugin"
			echo ""
			echo "[i] -q"
			echo "	- queries by type AAAA, A, SOA, TXT, PTR, ANY, SRV, IPV4, IPV6"
			echo ""
			echo "[i] -t"
			echo "  - Show a TOP number of queries by host"
		;;
		version)
			echo "[v] plugin by @deividgdt https://github.com/deividgdt - version: ${plugin_version}"
		;;
	esac
}

function apiCall() {
	local obj=$1
	
	pihole_api_tempfile="${current_dir}/pihole_api_${obj}.tmp"
	
	case $obj in 
		"summary")
			pihole_api_output=$(curl --insecure "${protocol:-http}://${pihole_ipadd}/admin/api.php?${obj}&auth=${api_token}" 2> /dev/null | sed 's/","/\n/g ; s/"//g' > ${pihole_api_tempfile})
		;;
		"getQueryTypes")
			pihole_api_output=$(curl --insecure "${protocol:-http}://${pihole_ipadd}/admin/api.php?${obj}&auth=${api_token}" 2> /dev/null | sed "s,),,g ; s,(,,g ; s/,\"/\n/g ; s/\"//g" > ${pihole_api_tempfile})
		;;
		"getQuerySources")
			pihole_api_output=$(curl --insecure "${protocol:-http}://${pihole_ipadd}/admin/api.php?${obj}&auth=${api_token}" 2> /dev/null | sed 's,{"top_sources":{",,g ; s/,"/\n/g ; s/"//g ; s/}//g ; s/|/:/g' > ${pihole_api_tempfile})
	esac
}

function getApiToken() {
	# Default token file location
	api_token_file="${current_dir}/apihole.token"
	
	# If the file does not exist
	if [ ! -f ${api_token_file} ]; then
		info token
	else
		export api_token=$(cat ${api_token_file})
		# If the the api_token var is NULL because the file is empty (?)
		if [ -z ${api_token} ]; then 
			echo "[e] Token is NULL"; 
			info token 
		fi
	fi
}

function functSummary() {
	# Calling the API
	apiCall "summary" 

	# The summary option passed
	case "${summary_opt}" in
		clients)	
			unique_clients=$(cat ${pihole_api_tempfile} | grep unique_clients | cut -f2 -d":")
			echo "THERE ARE ${unique_clients} HOSTS UP|Total=${unique_clients}"
		;;
		queries)	
			dns_queries_today=$(cat ${pihole_api_tempfile} | grep dns_queries_today | cut -f2 -d":")
			echo "DNS QUERIES TODAY ${dns_queries_today}|Total=${dns_queries_today}"
		;;
		ads)		
			ads_percentage_today=$(cat ${pihole_api_tempfile} | grep ads_percentage_today | cut -f2 -d":")
			ads_blocked_today=$(cat ${pihole_api_tempfile} | grep ads_blocked_today | cut -f2 -d":")
			echo "ADS BLOCKED TODAY ${ads_blocked_today} , PERCENTAGE = ${ads_percentage_today} %|Total=${ads_blocked_today} Percentage=${ads_percentage_today}%"
		;;
		
		*)
			echo "Incorrect arugment > ${summary_opt} < for the option -s";
			info "usage"
			exit 1;
		;;
	esac
}

function functGetQueryTypes() {
	
	# Calling the api
	apiCall "getQueryTypes" "${api_token}"
	
	# Local vars for query types
	local ipv4=$(cat ${pihole_api_tempfile} | grep -io "ipv4:.*" | cut -f2 -d":")
	local ipv6=$(cat ${pihole_api_tempfile} | grep -io "ipv6:.*" | cut -f2 -d":")
	local any=$(cat ${pihole_api_tempfile} | grep -io "any:.*" | cut -f2 -d":")
	local srv=$(cat ${pihole_api_tempfile} | grep -io "srv:.*" | cut -f2 -d":")
	local soa=$(cat ${pihole_api_tempfile} | grep -io "soa:.*" | cut -f2 -d":")
	local ptr=$(cat ${pihole_api_tempfile} | grep -xi "ptr:.*"  | cut -f2 -d":")
	local naptr=$(cat ${pihole_api_tempfile} | grep -io "naptr:.*" | cut -f2 -d":")
	local txt=$(cat ${pihole_api_tempfile} | grep -io "txt:.*" | sed 's,},,g' | cut -f2 -d":")
	
	echo "NUMBER OF QUERIES BY TYPE IPV4=${ipv4}% , IPV6=${ipv6}% , ANY=${any}% , SRV=${srv}% , SOA=${soa}% , PTR=${ptr}% , NAPTR=${naptr}% , TXT=${txt}% |IPV4=${ipv4}% IPV6=${ipv6}% ANY=${any}% SRV=${srv}% SOA=${soa}% PTR=${ptr}% TXT=${txt}%"
	
}

function functGetQuerySources() {

	# Calling the api
	apiCall "getQuerySources" "${api_token}"

	while read line; do  
		check_columns=$(echo $line | sed 's,:, ,g' | wc -w)
		host_name=$(echo $line | cut -f1 -d":")
		
		if [[ "${check_columns}" == "3" ]]; then
			columns="3"
		elif [[ "${check_columns}" == "2" ]]; then
			columns="2"
		else
			echo "Error formatting the list"
			exit 1;
		fi
		
		host_queries=$(echo $line | cut -f$columns -d":")
		
		if [ -z "${host_queries}" ]; then host_queries="0"; fi
		
		message="${message} ${host_name}=${host_queries}"
	done < ${pihole_api_tempfile}
	
	echo "TOP HOSTS BY QUERIES ${message}|${message}" 
}


if [ $# -eq 0 ]; then
	info "usage"
	exit 1;
fi

# The options passed by the user
while getopts "h:s:iqp:t" opt; do
	case "$opt" in
		h ) 
			pihole_ipadd=$OPTARG						;;
		s ) 
			summary_selected="y"
			summary_opt=$OPTARG							;;
		q ) 
			query_type_selected="y" 					;;
		p ) 
			protocol="$OPTARG" 							;;
		i ) 
			info "version"
			exit 0										;;
		t )
			query_sources_selected="y"					;;
		\?) 
			echo "[e] Invalid option. -$OPTARG" 
			exit 1										;;
	esac
done

# The values passed by the user
if [ -z ${pihole_ipadd} ]; then 
	echo "[i] Please enter the Pihole IP address as follow: -h pihole_ipaddress"; 
	exit 1;
else
	# We get the API Token
	getApiToken

	if [[ "${summary_selected}" == "y" ]]; then
		# Calling the summary function
		functSummary
		exit 0;
	elif [[ "${query_type_selected}" == "y" ]]; then
		# Calling the Query Types funct
		functGetQueryTypes
		exit 0;
	elif [[ "${query_sources_selected}" == "y" ]]; then
		functGetQuerySources
		exit 0;
	else
		info "usage"
	fi
	
	# Just delete the temp file
	rm -f ${pihole_api_tempfile}
fi
